blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomepageView, ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, \
    ClientDeleteView, MailingMessageDeleteView, MailingMessageDetailView, MailingMessageUpdateView, \
    MailingMessageCreateView, MailingMessageListView, MailingSettingsDeleteView, MailingSettingsDetailView, \
    MailingSettingsUpdateView, MailingSettingsCreateView, MailingSettingsListView, MailingLogListView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomepageView.as_view(), name='mailing'),
    path('client', cache_page(60)(ClientListView.as_view()), name='list_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('client/detail/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('message', cache_page(60)(MailingMessageListView.as_view()), name='list_message'),
    path('message/create/', MailingMessageCreateView.as_view(), name='create_message'),
    path('message/edit/<int:pk>/', MailingMessageUpdateView.as_view(), name='edit_message'),
    path('message/detail/<int:pk>/', MailingMessageDetailView.as_view(), name='view_message'),
    path('message/delete/<int:pk>/', MailingMessageDeleteView.as_view(), name='delete_message'),
    path('mailingsettings', MailingSettingsListView.as_view(), name='list_settings'),
    path('mailingsettings/create/', MailingSettingsCreateView.as_view(), name='create_settings'),
    path('mailingsettings/edit/<int:pk>/', MailingSettingsUpdateView.as_view(), name='edit_settings'),
    path('mailingsettings/detail/<int:pk>/', MailingSettingsDetailView.as_view(), name='view_settings'),
    path('mailingsettings/delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='delete_settings'),
    path('mailinglog/', MailingLogListView.as_view(), name='list_logs')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, generate_new_password, verify, \
    ProfileDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/delete/<int:pk>', ProfileDeleteView.as_view(), name='delete'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('verify/', verify),

]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    view_count = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    slug = models.SlugField(**NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

mailing/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    fullname = models.CharField(max_length=100, verbose_name='Фамилия Имя')
    email = models.EmailField(max_length=100, unique=True, verbose_name='Почта')
    comment = models.TextField(verbose_name='Сообщение', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Письмо')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class MailingSettings(models.Model):
    FREQUENCY = [
        ('daily', 'один раз в день'),
        ('weekly', 'один раз в неделю'),
        ('monthly', 'один раз в месяц')
    ]
    STATUS = [
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена')
    ]

    start_time = models.TimeField(default=timezone.now, verbose_name='Время отправления рассылки')
    stop_time = models.TimeField(default=timezone.now, verbose_name='Время окончания рассылки')
    frequency = models.CharField(max_length=50, choices=FREQUENCY, verbose_name='Переодичность')
    status = models.CharField(max_length=50, choices=STATUS, verbose_name='статус')
    client = models.ManyToManyField('Client', verbose_name='клиент')
    message = models.ForeignKey('MailingMessage', on_delete=models.CASCADE, verbose_name='Сообщение')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f'Рассылка {self.pk}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLog(models.Model):
    STATUS = [
        ('successfully', 'успешно'),
        ('fatally', 'фатально')
    ]

    datatime = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=50, choices=STATUS, verbose_name='статус попытки')
    serv_response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Рассылка')
    client = models.EmailField(verbose_name='Клиент', **NULLABLE)

    def __str__(self):
        return f'Лог Рассылки: {self.pk}({self.status})'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms
from blog.forms import StyleFormMixin
from mailing.models import Client, MailingMessage, MailingSettings


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ('fullname', 'email', 'comment',)


class MailingMessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = ('subject', 'body',)


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('start_time', 'stop_time', 'frequency', 'status', 'client', 'message')


class ModeratorMailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('status',)

mailing/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Blog
from mailing.forms import ClientForm, MailingMessageForm, MailingSettingsForm, ModeratorMailingSettingsForm
from mailing.models import Client, MailingMessage, MailingSettings, MailingLog
from mailing.services import get_message


class HomepageView(TemplateView):
    """Отображение главной страницы"""
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailing_settings'] = len(MailingSettings.objects.all())
        context_data['mailing_active'] = MailingSettings.objects.filter(status='launched').count()
        context_data['client'] = len(Client.objects.all())
        context_data['blog_list'] = random.sample(list(Blog.objects.all()), 3)

        return context_data


class MailingLogListView(LoginRequiredMixin, ListView):
    """Отображение списка рассылок"""
    model = MailingLog

    def get_queryset(self):
        """Функция для просмотра только своих логов"""
        if self.request.user.groups.filter(name='mailing_mod').exists():
            return MailingLog.objects.all()
        queryset = MailingLog.objects.filter(mailing__user=self.request.user)
        return queryset


class ClientListView(LoginRequiredMixin, ListView):
    """Отображение списка клиентов"""
    model = Client

    def get_queryset(self):
        """Функция для просмотра только своих клиентов"""
        queryset = super().get_queryset().filter()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(user=self.request.user)

        return queryset


class ClientCreateView(CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:list_client')

    def form_valid(self, form):
        """Функция для присвоения клиента к пользователю"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    """Редактирование клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:list_client')


class ClientDetailView(DetailView):
    """Просмотр клиента"""
    model = Client


class ClientDeleteView(DeleteView):
    """Удаление клиента"""
    model = Client
    success_url = reverse_lazy('mailing:list_client')


class MailingMessageListView(LoginRequiredMixin, ListView):
    """Отображение списка сообщений"""
    model = MailingMessage

    def get_queryset(self):
        """Функция, позволяющая просматривать только своих клиентов"""
        queryset = super().get_queryset().filter()
        if self.request.user.groups.filter(name='mailing_mod').exists():
            return queryset
        if not self.request.user.is_superuser:
            queryset = queryset.filter(user=self.request.user)

        return queryset


class MailingMessageCreateView(CreateView):
    """Создание сообщения"""
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('mailing:list_message')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingMessageUpdateView(UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('mailing:list_message')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MailingMessageDetailView(DetailView):
    """Просмотр сообщения"""
    model = MailingMessage


class MailingMessageDeleteView(DeleteView):
    """Удаление сообщения"""
    model = MailingMessage
    success_url = reverse_lazy('mailing:list_message')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MailingSettingsListView(LoginRequiredMixin, ListView):
    """Отображение списка рассылок"""
    model = MailingSettings

    def get_context_data(self, **kwargs):
        """Кеширование сообщений"""
        context_data = super().get_context_data(**kwargs)
        context_data['message'] = get_message()
        return context_data

    def get_queryset(self):
        queryset = super().get_queryset().filter()
        if self.request.user.groups.filter(name='mailing_mod').exists():
            return queryset
        if not self.request.user.is_superuser:
            queryset = queryset.filter(user=self.request.user)

        return queryset


class MailingSettingsCreateView(CreateView):
    """Создание рассылок"""
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:list_settings')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingSettingsUpdateView(UpdateView):
    """Редактирование рассылок"""
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:list_settings')

    def get_form_class(self):
        if self.object.user == self.request.user:
            return MailingSettingsForm
        if self.request.user.groups.filter(name='mailing_mod').exists():
            return ModeratorMailingSettingsForm


class MailingSettingsDetailView(DetailView):
    """Просмотр рассылок"""
    model = MailingSettings


class MailingSettingsDeleteView(DeleteView):
    """Удаление рассылок"""
    model = MailingSettings
    success_url = reverse_lazy('mailing:list_settings')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.object.user != self.request.user:
            raise Http404
        return self.object

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog Template for Bootstrap</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>

<body>

<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="text-muted" href="{% url 'blog:list_blog' %}">Блог</a>
                <a class="text-muted" href="{% url 'mailing:list_client' %}">Клиенты</a>
                <a class="text-muted" href="{% url 'mailing:list_message' %}">Сообщения</a>
                <a class="text-muted" href="{% url 'mailing:list_settings' %}">Рассылки</a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="{% url 'mailing:mailing' %}">Главная</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="mx-3">
                        <circle cx="10.5" cy="10.5" r="7.5"></circle>
                        <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                    </svg>
                </a>
                {% if user.is_authenticated %}
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:profile' %}">Профиль</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:login' %}">Войти</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
</div>
<footer class="blog-footer">
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script>
    Holder.addTheme('thumb', {
       bg: '#55595c',
       fg: '#eceeef',
       text: 'Thumbnail'
     });
</script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента "{{ object.fullname }}"</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'mailing:list_client' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% block content%}

<h2 class="display-4">Blog</h2>

<div class="btn-group">
    <div class="nav-scroller py-4 mb-2">
        <a href="{% url 'mailing:edit_client' object.pk %}">Изменить</a>
        <a href="{% url 'mailing:delete_client' object.pk %}">Удалить</a>
    </div>
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <div class="card flex-md-row mb-4 box-shadow md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h3 class="mb-0">
                    <a class="text-dark">{{object.fullname|title}}</a>
                </h3>
                <div class="mb-1 text-muted">{{ object.email }}</div>
                <p class="card-text mb-auto">{{ object.comment }}</p>
                <a href="#"></a>
                <div class="mb-1 text-muted">Ппользователь: {{ object.user }}</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content%}

<h4 class="display-12">Список моих клиентов</h4>
<div class="nav-scroller py-2 mb-2">
    <a href="{% url 'mailing:create_client' %}">Добавить Клиента</a>
</div>

<div class="row mb-2">
    {% for object in object_list %}
    <div class="col-md-6">
        <div class="card flex-md-row mb-2 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h4>
                    <strong class="d-inline-block">
                        <a class="text-success" href="{% url 'mailing:view_client' object.pk %}">{{object.fullname|title}}</a>
                    </strong>
                </h4>
                <div class="mb-1 text-muted">{{ object.email }}</div>
                <p class="card-text mb-auto">{{ object.comment }}</p>
                <div class="btn-group">
                    <div class="nav-scroller py-4 mb-2">
                        <a href="{% url 'mailing:edit_client' object.pk %}">Изменить</a>
                        <a href="{% url 'mailing:delete_client' object.pk %}">Удалить</a>
                    </div>
                </div>
                <div class="mb-1 text-muted">Пользователь: {{ object.user.first_name }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content%}
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <a class="p-2 text-muted">Количество рассылок: {{ mailing_settings }}</a>
        <a class="p-2 text-muted">Количество активных рассылок: {{ mailing_active }}</a>
        <a class="p-2 text-muted">Всего пользователей: {{ client }}</a>
    </nav>
</div>
<div class="row mb-2">
    {% for object in blog_list %}
    <div class="col-md-12">
        <div class="card flex-md-row mb-2 box-shadow h-md-350">
            <div class="card-body d-flex flex-column align-items-start">
                <h4>
                    <strong class="d-inline-block">
                        <a class="text-success" href="{% url 'blog:view_blog' object.slug %}">{{object.title|title}}</a>
                    </strong>
                </h4>
                <div class="mb-1 text-muted">{{ object.date }}</div>
                <div class="mb-1 text-muted">Просмотры: {{ object.view_count }}</div>
                <p class="card-text mb-auto">{{ object.content|slice:":1000" }}...</p>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block"
                 src="{{ object.image|mymedia }}" style="width: 180px; height: 240px"
                 alt="Card image cap">
        </div>
    </div>
    {% endfor %}
</div>
<div class="btn-group">
    <div class="nav-scroller py-4 mb-2">
        <a href="{% url 'blog:list_blog'%}">Смотреть все статьи</a>

    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailinglog_list.html
{% extends 'mailing/base.html' %}
{% load custom_tags %}
{% block content%}

<h4 class="display-12">Список отправленных рассылок</h4>


<div class="row mb-2">
    {% for object in object_list %}
    <div class="col-md-12">
        <div class="card flex-md-row mb-2 box-shadow h-md-150">
            <div class="card-body d-flex flex-column align-items-start">
                <div class="nav-scroller">
                    <nav class="nav d-flex justify-content-between">
                        <a class="p-2 text-muted">{{object.datatime}}</a>
                        <a class="p-2 text-muted">{{ object.status }}</a>
                        <a class="p-2 text-muted">{{ object.client }}</a>
                        <a class="p-2 text-muted">{{ object.mailing.message }}</a>
                    </nav>
                </div>
                {% if object.serv_response %}
                <div class="text-muted">{{ object.serv_response }}</div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_detail.html
{% extends 'mailing/base.html' %}
{% load custom_tags %}
{% block content%}

<h2 class="display-4">Blog</h2>

<div class="btn-group">
    {% if user|has_group:"mailing_mod" %}
    {% endif %}
    {% if object.user == user %}
    <div class="nav-scroller py-4 mb-2">
        <a href="{% url 'mailing:edit_message' object.pk %}">Изменить</a>
        <a href="{% url 'mailing:delete_message' object.pk %}">Удалить</a>
    </div>
    {% endif %}
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <div class="card flex-md-row mb-4 box-shadow md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h3 class="mb-0">
                    <a class="text-dark">{{object.subject|title}}</a>
                </h3>
                <p class="card-text mb-auto">{{ object.body }}</p>
                <a href="#"></a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailingmessage_list.html
{% extends 'mailing/base.html' %}
{% load custom_tags %}
{% block content%}

<h4 class="display-12">Список моих сообщений</h4>
<div class="nav-scroller py-2 mb-2">
    <a href="{% url 'mailing:create_message' %}">Добавить сообщение</a>
</div>

<div class="row mb-2">
    {% for object in object_list %}
    <div class="col-md-6">
        <div class="card flex-md-row mb-2 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h4>
                    <strong class="d-inline-block">
                        <a class="text-success" href="{% url 'mailing:view_message' object.pk %}">{{object.subject|title}}</a>
                    </strong>
                </h4>
                <div class="btn-group">
                    {% if user|has_group:"mailing_mod" %}
                    {% endif %}
                    {% if object.user == user %}
                    <div class="nav-scroller py-4 mb-2">
                        <a href="{% url 'mailing:edit_message' object.pk %}">Изменить</a>
                        <a href="{% url 'mailing:delete_message' object.pk %}">Удалить</a>
                    </div>
                    {% endif %}
                </div>
                <div class="mb-1 text-muted">Пользователь: {{ object.user.first_name }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_detail.html
{% extends 'mailing/base.html' %}
{% load custom_tags %}
{% block content%}

<h2 class="display-4">Blog</h2>

<div class="btn-group">
    <div class="nav-scroller py-4 mb-2">
        {% if user|has_group:"mailing_mod" %}
        <a href="{% url 'mailing:edit_settings' object.pk %}">Изменить</a>
        {% endif %}
        {% if object.user == user %}
        <a href="{% url 'mailing:edit_settings' object.pk %}">Изменить</a>
        <a href="{% url 'mailing:delete_settings' object.pk %}">Удалить</a>
        {% endif %}
    </div>
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <div class="card flex-md-row mb-4 box-shadow md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h4 class="mb-0">
                    <a class="text-dark">Время начала отправления: {{object.start_time}}</a>
                </h4>
                <div class="mb-1 text-muted">Переодичность: {{ object.frequency }}</div>
                <p class="card-text mb-auto">Статус: {{ object.status }}</p>
                <a href="#"></a>
                <div class="mb-1 text-muted">Сообщение: {{ object.message }}</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'mailing/base.html' %}
{% load custom_tags %}
{% block content%}

<h4 class="display-12">Список моих рассылок</h4>
<div class="nav-scroller p-2 py-2 mb-2">
    <a href="{% url 'mailing:create_settings' %}">Добавить Рассылку</a>
    <a href="{% url 'mailing:list_logs' %}">Отчет о рассылках</a>
</div>

<div class="row mb-2">
    {% for object in object_list %}
    <div class="col-md-6">
        <div class="card flex-md-row mb-2 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h4>
                    <strong class="d-inline-block">
                        <a class="text-success" href="{% url 'mailing:view_settings' object.pk %}">{{object.message.subject}}</a>
                    </strong>
                </h4>
                <div class="mb-1 text-muted">Время отправления:{{ object.start_time }}</div>
                <div class="mb-1 text-muted">Время завершения:{{ object.stop_time }}</div>
                <p class="card-text mb-auto">Переодичность: {{ object.frequency }}</p>
                <p class="card-text mb-auto">Сообщение: {{ object.message }}</p>
                <div class="btn-group">
                    <div class="nav-scroller py-2 mb-2">
                        {% if user|has_group:"mailing_mod" %}
                        <a href="{% url 'mailing:edit_settings' object.pk %}">Изменить</a>
                        {% endif %}
                        {% if object.user == user %}
                        <a href="{% url 'mailing:edit_settings' object.pk %}">Изменить</a>
                        <a href="{% url 'mailing:delete_settings' object.pk %}">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                <div class="mb-1 text-muted">Пользователь: {{ object.user.first_name }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}