blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    view_count = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    slug = models.SlugField(**NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms

from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForms(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from pytils.translit import slugify
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.forms import BlogForms
from blog.models import Blog


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    """Отображения страницы блога"""
    model = Blog
    slug_url_kwarg = 'slug'

    def get_object(self, queryset=None):
        """Реализация счетчика просмотров"""
        slug = self.kwargs.get('slug')
        blog = self.model.objects.get(slug=slug)
        blog.view_count += 1
        blog.save()
        return blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    """Создание блога"""
    model = Blog
    form_class = BlogForms
    success_url = reverse_lazy('blog:list_blog')

    def get_form_class(self):
        if not self.request.user.groups.filter(name='blog_mod').exists():
            raise Http404
        return BlogForms

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save()
            blog.slug = slugify(blog.title)
            blog.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование блога"""
    model = Blog
    form_class = BlogForms
    success_url = reverse_lazy('blog:list_blog')

    def get_form_class(self):
        if not self.request.user.groups.filter(name='blog_mod').exists():
            raise Http404
        return BlogForms


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление блога"""
    model = Blog
    success_url = reverse_lazy('blog:list_blog')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.groups.filter(name='blog_mod').exists():
            raise Http404
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить запись "{{ object.title }}"</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blog:list_blog' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% load blog_tags %}
{% block content%}

<h2 class="display-4">Blog</h2>

<div class="btn-group">
    <div class="nav-scroller py-4 mb-2">
        {% if user|has_group:"blog_mod" %}
        <a href="{% url 'blog:edit_blog' object.slug %}">Изменить</a>
        <a href="{% url 'blog:delete_blog' object.slug %}">Удалить</a>
        {% endif %}
    </div>
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <div class="card flex-md-row mb-4 box-shadow md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h3 class="mb-0">
                    <a class="text-dark">{{object.title|title}}</a>
                </h3>
                <div class="mb-1 text-muted">{{ object.date }}</div>
                <p class="card-text mb-auto">{{ object.content }}</p>
                <a href="#"></a>
                <div class="mb-1 text-muted">Просмотры: {{ object.view_count }}</div>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block"
                 src="{{ object.image|mymedia }}" style="width: 400px; height: 550px">
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% load blog_tags %}
{% block content%}


<div class="nav-scroller py-4 mb-2">
    {% if user|has_group:"blog_mod" %}
    <a href="{% url 'blog:create_blog' %}">Добавить Блог</a>
    {% endif %}
</div>

<div class="row mb-2">
    {% for object in object_list %}
    <div class="col-md-6">
        <div class="card flex-md-row mb-2 box-shadow h-md-350">
            <div class="card-body d-flex flex-column align-items-start">
                <h4>
                    <strong class="d-inline-block">
                        <a class="text-success" href="{% url 'blog:view_blog' object.slug %}">{{object.title|title}}</a>
                    </strong>
                </h4>
                <div class="mb-1 text-muted">{{ object.date }}</div>
                <div class="mb-1 text-muted">Просмотры: {{ object.view_count }}</div>
                <p class="card-text mb-auto">{{ object.content|slice:":100" }}...</p>
                <div class="btn-group">
                    <div class="nav-scroller py-4 mb-2">
                        {% if user|has_group:"blog_mod" %}
                        <a href="{% url 'blog:edit_blog' object.slug %}">Изменить</a>
                        <a href="{% url 'blog:delete_blog' object.slug %}">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block"
                 src="{{ object.image|mymedia }}" style="width: 180px; height: 240px"
                 alt="Card image cap">
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}