blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, generate_new_password, verify, \
    ProfileDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/delete/<int:pk>', ProfileDeleteView.as_view(), name='delete'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('verify/', verify),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(max_length=150, unique=True, verbose_name='Почта')
    verified = models.BooleanField(default=False, verbose_name='подтвержден')
    verification_code = models.IntegerField(verbose_name='ключ подтверждения', **NULLABLE)

    is_blocked = models.BooleanField(default=False, verbose_name='Блокировка')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password',)


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import secrets
import string

from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from users.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from users.models import User
from users.services import send_new_password, send_verification_link


class LoginView(BaseLoginView):
    """Страница входа"""
    form_class = UserLoginForm
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    """Страница выхода"""
    pass


class RegisterView(CreateView):
    """Страница регистрации"""
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        """Отправления ссылки для подтверждения регистрации"""
        verification_code = ''.join([str(random.randint(0, 9)) for _ in range(6)])
        form.verification_code = verification_code
        user = form.save()
        user.verification_code = verification_code
        send_verification_link(user.email, verification_code)
        return super().form_valid(form)


class ProfileDeleteView(DeleteView):
    """Страница удаления профиля"""
    model = User
    success_url = reverse_lazy('mailing:mailing')


def verify(request):
    code = int(request.GET.get('code'))
    user = User.objects.get(verification_code=code)
    user.verified = True
    user.save()
    return render(request, 'users/verify.html')


class ProfileView(UpdateView):
    """Страница профиля пользователя"""
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    """Генерация пароля"""
    new_password = ''.join(secrets.choice(string.ascii_letters + string.digits) for _ in range(12))
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы действительно хотите удалить свой аккаунт? "{{ object.first_name }}"</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'users:profile' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Мой профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                    <a href="{% url 'users:delete' object.pk %}" class="btn btn-danger">Удалить профиль</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verify.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Спасибо за регистрацию</h1>
    <h2 class="display-6">Ваша почта подтверждена</h2>
</div>

{% endblock %}